server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.101.216.55:3306/opgg_clone?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  lol:
    leaderboard: https://kr.api.riotgames.com/lol/league-exp/v4/entries/RANKED_SOLO_5x5



