version: '3.7'
services:
  app:
    container_name: spring-app
    image: openjdk:11-jdk
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["./gradlew", "bootrun"]
    restart: always